// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3zczDsoQh0K1Z1uRM7DrIrf8YIMDnvc8',
    appId: '1:9554136059:web:8076f6456008d339ded95e',
    messagingSenderId: '9554136059',
    projectId: 'auth-ef804',
    authDomain: 'auth-ef804.firebaseapp.com',
    storageBucket: 'auth-ef804.firebasestorage.app',
    measurementId: 'G-TTLY1E80XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfRY8FD-rYFAoq4LKMlgkvMr0qJrOLaSE',
    appId: '1:9554136059:android:1fccfd68b8e08633ded95e',
    messagingSenderId: '9554136059',
    projectId: 'auth-ef804',
    storageBucket: 'auth-ef804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2c2FwtuJgf7duQaz09uLFRlWlUtj8jQY',
    appId: '1:9554136059:ios:8c35ae997f2d343dded95e',
    messagingSenderId: '9554136059',
    projectId: 'auth-ef804',
    storageBucket: 'auth-ef804.firebasestorage.app',
    iosBundleId: 'com.example.splitwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2c2FwtuJgf7duQaz09uLFRlWlUtj8jQY',
    appId: '1:9554136059:ios:8c35ae997f2d343dded95e',
    messagingSenderId: '9554136059',
    projectId: 'auth-ef804',
    storageBucket: 'auth-ef804.firebasestorage.app',
    iosBundleId: 'com.example.splitwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3zczDsoQh0K1Z1uRM7DrIrf8YIMDnvc8',
    appId: '1:9554136059:web:1d3e215b3f8bdc3dded95e',
    messagingSenderId: '9554136059',
    projectId: 'auth-ef804',
    authDomain: 'auth-ef804.firebaseapp.com',
    storageBucket: 'auth-ef804.firebasestorage.app',
    measurementId: 'G-5WEDKS0KFV',
  );
}
